name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the $default-branch branch
  push:
    branches: [$default-branch]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # uses .minimum_zig_version from build.zig.zon
      - uses: mlugg/setup-zig@v1

      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install mesa-common-dev libgl-dev libglx-dev libegl-dev libpulse-dev libxext-dev libxfixes-dev libxrender-dev libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev

      - name: Compile
        run: zig build -Duse-lld=false # compile all backends

      - name: Run tests
        run: zig build test -Dbackend=testing -Duse-lld=false

  test-windows:
    runs-on: windows-latest
    name: Build and test Windows

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # uses .minimum_zig_version from build.zig.zon
      - uses: mlugg/setup-zig@v1

      - name: Compile Dx11
        run: zig build -Dbackend=dx11

      - name: Run tests
        run: zig build test -Dbackend=testing
